name: flow_stepper_widget_example
description: Example app for the flow_stepper_widget package
publish_to: 'none'
version: 0.0.3

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flow_stepper_widget:
    path: ../
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true 
