name: flow_stepper_widget
description: A lightweight, highly-customizable Flutter stepper/indicator widget with modern design and full styling control.
version: 0.0.2
homepage: https://github.com/danial2026/flow_stepper_widget

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
